# Path to the virtme-ng binary
vng_path: "vng"
# Command/script to run inside the VM (path + arguments)
cmd: "/usr/bin/echo 'hey'"
# Number of parallel VMs to run
parallel: 2
# Path to the output file for the report (if empty uses stdout)
out_path: ""
# show only the final report and not the individual VM outputs
report_only: false
# kernel versions to test
kernel_versions:
    - v5.15.197
    - v6.1.159
    - v6.6.119
